[package]
name = "kc-server"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
rdev = "0.5.3"
winapi = { version = "0.3.9", features = ["winuser"] }

[dependencies.zrpc]
path = "../../"
