[package]
name = "accounting-server"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
zrpc = { path = "../../", features = ["log"] }

[dependencies.test-domain]
path = "../test-domain"
